name = "PackageCompilerHelper"
uuid = "d133116e-6e7b-4696-be2a-2268182a7016"
authors = ["Dilum Aluthge"]
version = "0.1.0-DEV"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
